services:

    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    migrate:
        build:
            context: ../API # StreamTrack/API/
            dockerfile: ../Docker/Dockerfile.migrate
        depends_on:
            - db
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - DOTNET_RUNNING_IN_CONTAINER=true
            - OCI_REGION=${OCI_REGION}
            - SECRET_OCID=${SECRET_OCID}
            - STREAMTRACK_SECRET_JSON=${STREAMTRACK_SECRET_JSON}
        volumes:
            - ./MigrationScript.sh:/src/MigrationScript.sh:ro

    api:
        restart: unless-stopped
        build:
            context: ../API # StreamTrack/API/
            dockerfile: ../Docker/Dockerfile
        depends_on:
            - db
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - DOTNET_RUNNING_IN_CONTAINER=true
            - ASPNETCORE_URLS=http://+:6969
            - OCI_REGION=${OCI_REGION}
            - SECRET_OCID=${SECRET_OCID}
            - STREAMTRACK_SECRET_JSON=${STREAMTRACK_SECRET_JSON}
        volumes:
            - ./APIScript.sh:/app/APIScript.sh:ro
        ports:
            - "127.0.0.1:6969:6969"

    caddy:
        build:
            context: .
            dockerfile: Caddy.Dockerfile
        restart: always
        ports:
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./certs:/etc/caddy/certs:ro
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - api

volumes:
    pgdata:
    caddy_data:
    caddy_config:
